import { Box, Flex } from "@chakra-ui/react";
import Head from "next/head";
import { useState } from "react";
import Card from "../components/Card";

export default function Home({ data }) {
  const [advice, setAdvice] = useState(data.slip.advice);

  const generateAdvice = async () => {
    const res = await fetch("https://api.adviceslip.com/advice");
    const results = await res.json();
    setAdvice(results.slip.advice);
  };

  console.log(data);

  return (
    <>
      <Flex
        bg="hsl(218, 23%, 16%)"
        h="100vh"
        justify="center"
        align="center"
        maxW="1440px"
        minW="375px"
      >
        <Head>
          <title>Advice Generator App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon-32x32.png" />
        </Head>
        <Card
          advice={advice}
          id={data.slip.id}
          generateAdvice={generateAdvice}
        />
      </Flex>
    </>
  );
}

export async function getStaticProps(context) {
  const res = await fetch("https://api.adviceslip.com/advice");
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}
